import type { ToolDefinition } from "@/types";

/**
 * Single source of truth for every tool in the app.
 * status: "available" tools have a real page + working implementation at /tools/[slug].
 * status: "coming-soon" tools are listed for discoverability but are clearly labeled
 * and not clickable into a fake working page.
 */
export const TOOLS: ToolDefinition[] = [
  // Study
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, and sentences as you type.",
    category: "text",
    status: "available",
    clientSideOnly: true,
    keywords: ["words", "count", "length"],
  },
  {
    slug: "character-counter",
    name: "Character Counter",
    description: "Count characters including or excluding spaces.",
    category: "text",
    status: "available",
    clientSideOnly: true,
    keywords: ["characters", "count", "length"],
  },
  {
    slug: "sentence-counter",
    name: "Sentence Counter",
    description: "Count sentences and get average sentence length.",
    category: "text",
    status: "available",
    clientSideOnly: true,
    keywords: ["sentences", "count"],
  },
  {
    slug: "reading-time",
    name: "Reading Time Calculator",
    description: "Estimate how long a passage takes to read aloud or silently.",
    category: "text",
    status: "available",
    clientSideOnly: true,
    keywords: ["reading", "time", "speed"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text to uppercase, lowercase, title case, or sentence case.",
    category: "text",
    status: "available",
    clientSideOnly: true,
    keywords: ["case", "uppercase", "lowercase", "convert"],
  },
  {
    slug: "text-cleaner",
    name: "Text Cleaner",
    description: "Remove extra spaces, blank lines, and trailing whitespace.",
    category: "text",
    status: "available",
    clientSideOnly: true,
    keywords: ["clean", "whitespace", "spaces"],
  },
  {
    slug: "text-diff",
    name: "Text Comparison",
    description: "Compare two blocks of text and highlight the differences.",
    category: "text",
    status: "available",
    clientSideOnly: true,
    keywords: ["diff", "compare", "difference"],
  },
  {
    slug: "citation-generator",
    name: "Citation Generator",
    description: "Generate APA, MLA, and Chicago style citations.",
    category: "study",
    status: "coming-soon",
    clientSideOnly: true,
    keywords: ["citation", "reference", "bibliography"],
  },
  {
    slug: "random-study-picker",
    name: "Random Study Picker",
    description: "Randomly pick a subject or topic to study next.",
    category: "study",
    status: "coming-soon",
    clientSideOnly: true,
    keywords: ["random", "picker"],
  },
  {
    slug: "pomodoro",
    name: "Pomodoro Timer",
    description: "Focus and break intervals with a session counter.",
    category: "study",
    status: "available",
    clientSideOnly: true,
    keywords: ["pomodoro", "focus", "timer", "break"],
  },
  {
    slug: "exam-countdown",
    name: "Exam Countdown",
    description: "Track the days remaining until your next exam.",
    category: "student",
    status: "coming-soon",
    clientSideOnly: true,
    keywords: ["exam", "countdown", "deadline"],
  },

  // PDF & documents
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into a single document.",
    category: "pdf",
    status: "available",
    clientSideOnly: true,
    keywords: ["merge", "combine", "pdf"],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Extract a page range from a PDF into a new file.",
    category: "pdf",
    status: "available",
    clientSideOnly: true,
    keywords: ["split", "pdf", "extract pages"],
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract plain text content from a PDF file.",
    category: "pdf",
    status: "available",
    clientSideOnly: true,
    keywords: ["pdf", "text", "extract"],
  },
  {
    slug: "text-to-pdf",
    name: "Text to PDF",
    description: "Convert plain text into a downloadable PDF document.",
    category: "pdf",
    status: "available",
    clientSideOnly: true,
    keywords: ["text", "pdf", "convert"],
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert a PDF document into an editable Word file.",
    category: "pdf",
    status: "coming-soon",
    clientSideOnly: false,
    keywords: ["pdf", "word", "convert"],
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert a Word document into a PDF file.",
    category: "pdf",
    status: "coming-soon",
    clientSideOnly: false,
    keywords: ["word", "pdf", "convert"],
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages into JPG images.",
    category: "pdf",
    status: "coming-soon",
    clientSideOnly: true,
    keywords: ["pdf", "jpg", "image"],
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size while keeping it readable.",
    category: "pdf",
    status: "coming-soon",
    clientSideOnly: true,
    keywords: ["compress", "pdf", "reduce size"],
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate one or all pages in a PDF document.",
    category: "pdf",
    status: "coming-soon",
    clientSideOnly: true,
    keywords: ["rotate", "pdf"],
  },

  // Images
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Compress JPG, PNG, and WebP images in seconds.",
    category: "images",
    status: "available",
    clientSideOnly: true,
    keywords: ["compress", "image", "reduce size", "jpg", "png"],
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize an image by width, height, or preset dimensions.",
    category: "images",
    status: "available",
    clientSideOnly: true,
    keywords: ["resize", "image", "dimensions"],
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    description: "Convert between JPG, PNG, and WebP formats.",
    category: "images",
    status: "available",
    clientSideOnly: true,
    keywords: ["convert", "image", "jpg", "png", "webp"],
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    description: "Crop an image to a custom or preset aspect ratio.",
    category: "images",
    status: "coming-soon",
    clientSideOnly: true,
    keywords: ["crop", "image"],
  },

  // Calculators
  {
    slug: "gpa-calculator",
    name: "GPA Calculator",
    description: "Calculate your GPA quickly using your course grades.",
    category: "calculators",
    status: "available",
    clientSideOnly: true,
    keywords: ["gpa", "grade point average"],
  },
  {
    slug: "cgpa-calculator",
    name: "CGPA Calculator",
    description: "Calculate your cumulative GPA across multiple semesters.",
    category: "calculators",
    status: "available",
    clientSideOnly: true,
    keywords: ["cgpa", "cumulative gpa"],
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, increases, and decreases.",
    category: "calculators",
    status: "available",
    clientSideOnly: true,
    keywords: ["percentage", "percent"],
  },
  {
    slug: "grade-calculator",
    name: "Grade Calculator",
    description: "Work out the grade you need on a final exam.",
    category: "calculators",
    status: "available",
    clientSideOnly: true,
    keywords: ["grade", "exam", "final"],
  },
  {
    slug: "average-calculator",
    name: "Average Calculator",
    description: "Calculate the average of a list of numbers.",
    category: "calculators",
    status: "available",
    clientSideOnly: true,
    keywords: ["average", "mean"],
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate exact age in years, months, and days.",
    category: "calculators",
    status: "available",
    clientSideOnly: true,
    keywords: ["age", "birthday"],
  },
  {
    slug: "date-difference",
    name: "Date Difference Calculator",
    description: "Find the number of days between two dates.",
    category: "calculators",
    status: "available",
    clientSideOnly: true,
    keywords: ["date", "difference", "days between"],
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert between common length, weight, and volume units.",
    category: "calculators",
    status: "available",
    clientSideOnly: true,
    keywords: ["unit", "convert", "length", "weight"],
  },
  {
    slug: "scientific-calculator",
    name: "Scientific Calculator",
    description: "A full scientific calculator for quick calculations.",
    category: "calculators",
    status: "coming-soon",
    clientSideOnly: true,
    keywords: ["scientific", "calculator"],
  },

  // Student utilities
  {
    slug: "attendance-calculator",
    name: "Attendance Calculator",
    description: "Track attendance percentage and required classes.",
    category: "student",
    status: "coming-soon",
    clientSideOnly: true,
    keywords: ["attendance"],
  },
];

export function getAvailableTools(): ToolDefinition[] {
  return TOOLS.filter((t) => t.status === "available");
}

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export const CATEGORY_LABELS: Record<ToolDefinition["category"], string> = {
  study: "Study",
  pdf: "PDF & Documents",
  images: "Images",
  text: "Text",
  calculators: "Calculators",
  student: "Student",
};
